spring:
  application:
    name: brano
  profiles:
    default: local

mybatis:
  mapper-locations: classpath:mapper/kr/pe/ryudaewan/brano/**/dao/*Dao.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  info:
  #  title: brano API
    version: 0.0.1-SNAPSHOT
    description: brano API
