insert into users (uid, name, email, created_at, updated_at, deleted_at)
values (0, '관리자', 'admin@brano.com', now(), null, null);
insert into users (uid, name, email, created_at, updated_at, deleted_at)
values (1, '장원영', 'think@brano.com', now(), null, null);
insert into users (uid, name, email, created_at, updated_at, deleted_at)
values (2, '하지원', 'hahaha@brano.com', now(), null, null);
insert into users (uid, name, email, created_at, updated_at, deleted_at)
values ( 3, '오인혜', 'inhye@brano.com'
       , to_timestamp('2019-04-23 13:34:41', 'YYYY-MM-DD HH24:MI:SS')
       , to_timestamp('2019-05-21 18:12:13', 'YYYY-MM-DD HH24:MI:SS')
       , to_timestamp('2020-09-14 22:59:59', 'YYYY-MM-DD HH24:MI:SS'));

-- 스프링 시큐리티에서 기본 탑재한 메시지 번들 정보
INSERT INTO messages (locale, message_key, message_content, created_at, message_id)
VALUES ('ko', 'AbstractAccessDecisionManager.accessDenied','접근이 거부되었습니다.', now(), 0)
     , ('ko', 'AbstractLdapAuthenticationProvider.emptyPassword','비밀번호가 맞지 않습니다.', now(), 1)
     , ('ko', 'AbstractSecurityInterceptor.authenticationNotFound','SecurityContext에서 Authentication 객체를 찾을 수 없습니다.', now(), 2)
     , ('ko', 'AbstractUserDetailsAuthenticationProvider.badCredentials','자격 증명에 실패하였습니다.', now(), 3)
     , ('ko', 'AbstractUserDetailsAuthenticationProvider.credentialsExpired','자격 증명 유효 기간이 만료되었습니다.', now(), 4)
     , ('ko', 'AbstractUserDetailsAuthenticationProvider.disabled','유효하지 않은 사용자입니다.', now(), 5)
     , ('ko', 'AbstractUserDetailsAuthenticationProvider.expired','사용자 계정의 유효 기간이 만료 되었습니다.', now(), 6)
     , ('ko', 'AbstractUserDetailsAuthenticationProvider.locked','사용자 계정이 잠겨 있습니다.', now(), 7)
     , ('ko', 'AbstractUserDetailsAuthenticationProvider.onlySupports','UsernamePasswordAuthenticationToken만 지원합니다.', now(), 8)
     , ('ko', 'AccountStatusUserDetailsChecker.credentialsExpired','자격 증명 유효 기간이 만료되었습니다.', now(), 9)
     , ('ko', 'AccountStatusUserDetailsChecker.disabled','유효하지 않은 사용자입니다.', now(), 10)
     , ('ko', 'AccountStatusUserDetailsChecker.expired','사용자 계정의 유효 기간이 만료 되었습니다.', now(), 11)
     , ('ko', 'AccountStatusUserDetailsChecker.locked','사용자 계정이 잠겨 있습니다.', now(), 12)
     , ('ko', 'AclEntryAfterInvocationProvider.noPermission','domain object {1}에 대한 권한이 Authentication {0}에 없습니다.', now(), 13)
     , ('ko', 'AnonymousAuthenticationProvider.incorrectKey','제공된 AnonymousAuthenticationToken에는 필요로하는 key가 없습니다.', now(), 14)
     , ('ko', 'BindAuthenticator.badCredentials','자격 증명에 실패하였습니다.', now(), 15)
     , ('ko', 'BindAuthenticator.emptyPassword','비밀번호 항목이 비어 있습니다.', now(), 16)
     , ('ko', 'CasAuthenticationProvider.incorrectKey','제공된 CasAuthenticationToken에는 필요로 하는 key가 없습니다.', now(), 17)
     , ('ko', 'CasAuthenticationProvider.noServiceTicket','검증을 위한 CAS 서비스 티켓을 제공할 수 없습니다.', now(), 18)
     , ('ko', 'ConcurrentSessionControlAuthenticationStrategy.exceededAllowed','최대 세션 허용 수 {0}개를 초과하였습니다.', now(), 19)
     , ('ko', 'DigestAuthenticationFilter.incorrectRealm','응답 realm 이름 {0}과 시스템 realm 이름 {1}이 일치하지 않습니다.', now(), 20)
     , ('ko', 'DigestAuthenticationFilter.incorrectResponse','응답이 정확하지 않습니다.', now(), 21)
     , ('ko', 'DigestAuthenticationFilter.missingAuth','''auth'' QOP(quality of protection)를 위한 digest 값은 필수 항목입니다. 현재 header 값은 {0}입니다.', now(), 22)
     , ('ko', 'DigestAuthenticationFilter.missingMandatory','digest 값은 필수 항목입니다. 현재 header 값은 {0}입니다.', now(), 23)
     , ('ko', 'DigestAuthenticationFilter.nonceCompromised','Nonce 토큰이 손상되었습니다. 현재 nonce 값은 {0}입니다.', now(), 24)
     , ('ko', 'DigestAuthenticationFilter.nonceEncoding','Nonce 값이 Base64로 인코딩 되어있지 않습니다. 현재 nonce 값은 {0}입니다.', now(), 25)
     , ('ko', 'DigestAuthenticationFilter.nonceExpired','Nonce의 유효 기간이 만료되었거나 시간이 초과되었습니다.', now(), 26)
     , ('ko', 'DigestAuthenticationFilter.nonceNotNumeric','Nonce 토큰의 첫 글자는 숫자로 시작해야 합니다. 현재 nonce 값은 {0}입니다.', now(), 27)
     , ('ko', 'DigestAuthenticationFilter.nonceNotTwoTokens','Nonce는 두 개의 토큰을 만들어야 합니다. 현재 nonce 값은 {0}입니다.', now(), 28)
     , ('ko', 'DigestAuthenticationFilter.usernameNotFound','{0} ID를 찾을 수 없습니다.', now(), 29)
     , ('ko', 'JdbcDaoImpl.noAuthority','{0} 사용자는 권한이 없습니다.', now(), 30)
     , ('ko', 'JdbcDaoImpl.notFound','{0} 사용자를 찾을 수 없습니다.', now(), 31)
     , ('ko', 'LdapAuthenticationProvider.badCredentials','자격 증명에 실패하였습니다.', now(), 32)
     , ('ko', '#LdapAuthenticationProvider.badLdapConnection','Connection to LDAP server failed', now(), 33)
     , ('ko', 'LdapAuthenticationProvider.credentialsExpired','자격 증명 유효 기간이 만료되었습니다.', now(), 34)
     , ('ko', 'LdapAuthenticationProvider.disabled','유효하지 않은 사용자입니다.', now(), 35)
     , ('ko', 'LdapAuthenticationProvider.expired','사용자 계정의 유효 기간이 만료 되었습니다.', now(), 36)
     , ('ko', 'LdapAuthenticationProvider.locked','사용자 계정이 잠겨 있습니다.', now(), 37)
     , ('ko', 'LdapAuthenticationProvider.emptyUsername','ID에 공백은 허용되지 않습니다.', now(), 38)
     , ('ko', 'LdapAuthenticationProvider.onlySupports','UsernamePasswordAuthenticationToken만 지원합니다.', now(), 39)
     , ('ko', 'PasswordComparisonAuthenticator.badCredentials','자격 증명에 실패하였습니다.', now(), 40)
     , ('ko', 'PersistentTokenBasedRememberMeServices.cookieStolen','로그인 상태 유지를 위한 토큰이 일치하지 않습니다. 이전에 사용한 토큰이 타인으로부터 탈취 당했을 수 있습니다.', now(), 41)
     , ('ko', 'ProviderManager.providerNotFound','{0}을 위한 AuthenticationProvider를 찾을 수 없습니다.', now(), 42)
     , ('ko', 'RememberMeAuthenticationProvider.incorrectKey','제공된 RememberMeAuthenticationToken에는 필요로 하는 key가 없습니다.', now(), 43)
     , ('ko', 'RunAsImplAuthenticationProvider.incorrectKey','제공된 RunAsUserToken에는 필요로 하는 key가 없습니다.', now(), 44)
     , ('ko', 'SubjectDnX509PrincipalExtractor.noMatching','subjectDN: {0} 내에 매칭되는 패턴이 없습니다.', now(), 45)
     , ('ko', 'SwitchUserFilter.noCurrentUser','요청한 사용자를 찾을 수 없습니다.', now(), 46)
     , ('ko', 'SwitchUserFilter.noOriginalAuthentication','Authentication 객체의 원본을 찾을 수 없습니다.', now(), 47)
;

-- 메시지 샘플 데이터
INSERT INTO messages (message_id, locale, message_key, message_content, created_at)
VALUES (48, 'ko', 'validation.name.required', '이름은 필수입니다', now())
     , (49, 'ko', 'validation.email.invalid', '올바른 이메일을 입력하세요', now())
     , (50, 'ko', 'validation.email.required', '이메일은 필수입니다', now())
     , (51, 'ko', 'user.dup.email', '이미 쓰는 이메일로 새 사용자 등록 시도', now())
     , (52, 'ko', 'message.not.exist', '없는 메시지 코드입니다', now())
     , (53, 'ko', 'message.dup.key', '이 언어에는 같은 메시지 키로 등록한 메시지가 이미 있습니다', now())
;